### PR TITLE
Implemented node_module copying.

### PR DESCRIPTION
**Pull request by dacarley**

### CODE REVIEW

**Comment by dacarley** [comment]
Is there any interest in this PR?  It's been sitting for three weeks.

**Comment by Titozzz** [comment]
Gonna try it now :)

**Comment by JeanLebrument** [comment]
@dacarley How do you configure webpack config file to specify that I want to copy the node_modules ?

**Comment by dacarley** [comment]
Have a look at https://gist.github.com/dacarley/d84fbeb98a919b6c1a2b90aaf920b4f1

This is the config we're using in our project, which currently consists of 34 Lambdas, ApiGateway, SNS messaging, redis, etc.

One caveat is that some npm modules are completely incompatible with webpack, or the workarounds to get them to work aren't worth it.  To aide with this, I wrote a small module (`./nodeExternals`) that aides with this.  It's a heavily based on `webpack-node-externals`.

In our config, _most_ dependencies are bundled via webpack.  Anything that ends up in the `externals` array is copied into the serverless function's build folder, and gets included in the zip file that is uploaded to AWS Lambda.

I've been using my fork of `serverless-runtime-webpack` for about 6 weeks now, and haven't had any issues yet.

There _may_ be an issue with the latest versions of npm, which appear to flatten the `node_modules` folder.  I'm still running npm v2.15.5 -- this PR should be tested against the latest npm before being merged.

I can take a look at that sometime in the next couple of days.

**Comment by dacarley** [comment]
I just pushed another commit to allow for compatibility with npm 3.x (which has flattened node_modules folders).

**Pull request merged**
